/**
 * Executive Dashboard Template
 * High-level KPIs and metrics for executive overview
 */

import { DashboardTemplate, DashboardCategory, ChartType } from '@/types/dashboard';

export const ExecutiveDashboard: DashboardTemplate = {
  id: 'executive-dashboard',
  name: 'Executive Dashboard',
  description: 'High-level overview of LLM performance, costs, and security metrics',
  category: DashboardCategory.Executive,
  config: {
    name: 'Executive Dashboard',
    description: 'Real-time executive overview',
    category: DashboardCategory.Executive,
    widgets: [
      // Row 1: Key Metrics
      {
        id: 'total-requests',
        type: ChartType.SingleValueWithTrend,
        title: 'Total Requests',
        description: '24h total requests with trend',
        data_source: {
          type: 'metric',
          measurement: 'llm_requests_total',
          fields: ['count'],
          aggregation: {
            function: 'sum',
            window: '1h',
          },
          time_range: 'relative',
          relative_time: 'last_24h',
          filters: {},
          group_by: [],
        },
        visual_config: {
          color_scheme: '#3b82f6',
          options: {
            prefix: '',
            suffix: ' requests',
            trend_color: 'green',
          },
        },
        interaction_config: {
          enable_zoom: false,
          enable_pan: false,
          enable_drill_down: true,
          drill_down_target: 'performance-dashboard',
          enable_tooltip: true,
          enable_crosshair: false,
          clickable: true,
        },
        auto_refresh: true,
        refresh_interval: 30,
        layout: { x: 0, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
      },
      {
        id: 'avg-latency',
        type: ChartType.SingleValueWithTrend,
        title: 'Avg Latency',
        description: 'Average response latency',
        data_source: {
          type: 'metric',
          measurement: 'llm_latency',
          fields: ['latency_ms'],
          aggregation: {
            function: 'p95',
            window: '5m',
          },
          time_range: 'relative',
          relative_time: 'last_1h',
          filters: {},
          group_by: [],
        },
        visual_config: {
          color_scheme: '#10b981',
          options: {
            suffix: 'ms',
            trend_color: 'auto',
          },
        },
        interaction_config: {
          enable_zoom: false,
          enable_pan: false,
          enable_drill_down: true,
          enable_tooltip: true,
          enable_crosshair: false,
          clickable: true,
        },
        auto_refresh: true,
        refresh_interval: 30,
        layout: { x: 3, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
      },
      {
        id: 'total-cost',
        type: ChartType.SingleValueWithTrend,
        title: 'Total Cost',
        description: 'Daily LLM costs',
        data_source: {
          type: 'metric',
          measurement: 'llm_cost',
          fields: ['cost_usd'],
          aggregation: {
            function: 'sum',
            window: '1h',
          },
          time_range: 'relative',
          relative_time: 'last_24h',
          filters: {},
          group_by: [],
        },
        visual_config: {
          color_scheme: '#f59e0b',
          options: {
            prefix: '$',
            trend_color: 'inverse',
          },
        },
        interaction_config: {
          enable_zoom: false,
          enable_pan: false,
          enable_drill_down: true,
          drill_down_target: 'cost-dashboard',
          enable_tooltip: true,
          enable_crosshair: false,
          clickable: true,
        },
        auto_refresh: true,
        refresh_interval: 60,
        layout: { x: 6, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
      },
      {
        id: 'security-alerts',
        type: ChartType.SingleValue,
        title: 'Security Alerts',
        description: 'Active security alerts',
        data_source: {
          type: 'event',
          event_types: ['security'],
          severities: ['error', 'critical'],
          time_range: 'relative',
          relative_time: 'last_24h',
          filters: {},
          group_by: [],
        },
        visual_config: {
          color_scheme: '#ef4444',
          options: {
            threshold: {
              warning: 5,
              critical: 10,
            },
          },
        },
        interaction_config: {
          enable_zoom: false,
          enable_pan: false,
          enable_drill_down: true,
          drill_down_target: 'security-dashboard',
          enable_tooltip: true,
          enable_crosshair: false,
          clickable: true,
        },
        auto_refresh: true,
        refresh_interval: 30,
        layout: { x: 9, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
      },

      // Row 2: Request Volume Trend
      {
        id: 'request-volume',
        type: ChartType.TimeSeriesArea,
        title: 'Request Volume Over Time',
        description: 'Real-time request volume',
        data_source: {
          type: 'metric',
          measurement: 'llm_requests_total',
          fields: ['count'],
          aggregation: {
            function: 'sum',
            window: '5m',
          },
          time_range: 'relative',
          relative_time: 'last_24h',
          filters: {},
          group_by: ['model_id'],
        },
        visual_config: {
          color_scheme: ['#3b82f6', '#10b981', '#f59e0b', '#ef4444'],
          legend: { show: true, position: 'bottom' },
          x_axis: { label: 'Time', type: 'time', show_grid: true },
          y_axis: { label: 'Requests', type: 'linear', show_grid: true },
        },
        interaction_config: {
          enable_zoom: true,
          enable_pan: true,
          enable_drill_down: false,
          enable_tooltip: true,
          enable_crosshair: true,
          clickable: false,
        },
        auto_refresh: true,
        refresh_interval: 30,
        layout: { x: 0, y: 2, w: 12, h: 4, minW: 6, minH: 3 },
      },

      // Row 3: Performance and Cost
      {
        id: 'latency-distribution',
        type: ChartType.BoxPlot,
        title: 'Latency Distribution by Model',
        description: 'Statistical latency distribution',
        data_source: {
          type: 'metric',
          measurement: 'llm_latency',
          fields: ['latency_ms'],
          time_range: 'relative',
          relative_time: 'last_6h',
          filters: {},
          group_by: ['model_id'],
        },
        visual_config: {
          color_scheme: '#10b981',
          legend: { show: true, position: 'right' },
          x_axis: { label: 'Model', type: 'category' },
          y_axis: { label: 'Latency (ms)', type: 'linear', show_grid: true },
        },
        interaction_config: {
          enable_zoom: false,
          enable_pan: false,
          enable_drill_down: true,
          enable_tooltip: true,
          enable_crosshair: false,
          clickable: true,
        },
        auto_refresh: true,
        refresh_interval: 60,
        layout: { x: 0, y: 6, w: 6, h: 4, minW: 4, minH: 3 },
      },
      {
        id: 'cost-breakdown',
        type: ChartType.Donut,
        title: 'Cost Breakdown',
        description: 'Cost distribution by model',
        data_source: {
          type: 'metric',
          measurement: 'llm_cost',
          fields: ['cost_usd'],
          aggregation: {
            function: 'sum',
            window: '1h',
          },
          time_range: 'relative',
          relative_time: 'last_24h',
          filters: {},
          group_by: ['model_id'],
        },
        visual_config: {
          color_scheme: ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'],
          legend: { show: true, position: 'bottom' },
        },
        interaction_config: {
          enable_zoom: false,
          enable_pan: false,
          enable_drill_down: true,
          enable_tooltip: true,
          enable_crosshair: false,
          clickable: true,
        },
        auto_refresh: true,
        refresh_interval: 60,
        layout: { x: 6, y: 6, w: 6, h: 4, minW: 4, minH: 3 },
      },

      // Row 4: System Health
      {
        id: 'error-rate',
        type: ChartType.TimeSeriesLine,
        title: 'Error Rate',
        description: 'Error rate over time',
        data_source: {
          type: 'metric',
          measurement: 'llm_errors',
          fields: ['error_rate'],
          aggregation: {
            function: 'mean',
            window: '5m',
          },
          time_range: 'relative',
          relative_time: 'last_6h',
          filters: {},
          group_by: [],
        },
        visual_config: {
          color_scheme: '#ef4444',
          legend: { show: false, position: 'bottom' },
          x_axis: { label: 'Time', type: 'time', show_grid: true },
          y_axis: { label: 'Error Rate (%)', type: 'linear', show_grid: true, min: 0, max: 100 },
          thresholds: [
            { value: 1, color: '#f59e0b', label: 'Warning', operator: '>' },
            { value: 5, color: '#ef4444', label: 'Critical', operator: '>' },
          ],
        },
        interaction_config: {
          enable_zoom: true,
          enable_pan: true,
          enable_drill_down: false,
          enable_tooltip: true,
          enable_crosshair: true,
          clickable: false,
        },
        auto_refresh: true,
        refresh_interval: 30,
        layout: { x: 0, y: 10, w: 12, h: 3, minW: 6, minH: 2 },
      },
    ],
    layout_config: {
      grid_columns: 12,
      row_height: 60,
      compact_type: 'vertical',
      prevent_collision: false,
    },
    default_time_range: 'last_24h',
    auto_refresh: true,
    refresh_interval: 30,
    is_public: false,
    tags: ['executive', 'overview', 'kpi'],
  },
};
